#!/usr/bin/env bash
set -o errexit -o pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-}")" &>/dev/null && pwd 2>/dev/null)"

projectFolder=$(realpath "$here/..")
projectName=$(basename "$projectFolder")
imageName=${projectName##docker-}-dev
printf %s "$imageName"
